branch-defaults:
  master:
    environment: phillip-django-hello
    group_suffix: null
environment-defaults:
  django-env:
    branch: master
    repository: origin
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
